testBaseException... 

all is OK
	at ../testBaseException.cpp:48
	   ../bin/linux-x86/testBaseException
	   ../bin/linux-x86/testBaseException
	   /lib/libc.so.6: __libc_start_main()+0xe6
	   ../bin/linux-x86/testBaseException




exception 2
	at ../testBaseException.cpp:57
	   ../bin/linux-x86/testBaseException
	   ../bin/linux-x86/testBaseException
	   ../bin/linux-x86/testBaseException
	   /lib/libc.so.6: __libc_start_main()+0xe6
	   ../bin/linux-x86/testBaseException
exception 1
	at ../testBaseException.cpp:40
	   ../bin/linux-x86/testBaseException
	   ../bin/linux-x86/testBaseException
	   ../bin/linux-x86/testBaseException
	   ../bin/linux-x86/testBaseException
	   /lib/libc.so.6: __libc_start_main()+0xe6
	   ../bin/linux-x86/testBaseException
the root cause
	at ../testBaseException.cpp:31
	   ../bin/linux-x86/testBaseException
	   ../bin/linux-x86/testBaseException
	   ../bin/linux-x86/testBaseException
	   /lib/libc.so.6: __libc_start_main()+0xe6
	   ../bin/linux-x86/testBaseException


PASSED
